name: Deploy static site

on:
  push:
    branches: ["master","feat/*"]
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "static"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: wallet
      url: ${{ vars.WEBSITE }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          check-latest: true
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run deploy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist/'
      - shell: bash
        env:
          SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
          SSH_IDENTITY: ${{ secrets.SSH_IDENTITY }}
          SSH_IDENTITY_FILE: ${{ secrets.SSH_IDENTITY_FILE }}
        run: |
          touch ~/.ssh/config
          echo $SSH_CONFIG >> ~/.ssh/config
          echo $SSH_IDENTITY >> $SSH_IDENTITY_FILE
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOSTNAME }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        env:
          GHREF: ${{ GITHUB_REF_NAME }}
          RMFEAT: "feat/"
        run: |
          BRANCH=${GHREF//$RMFEAT/}
          rsync -avhPz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }}:~/branches/${BRANCH}
