name: Deploy static site

on:
  push:
    branches: ["master","feat/*"]
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "static"
  cancel-in-progress: true

jobs:
  deploy:
    # outputs:
    #   branch: ${{ steps.clean_branch.outputs.branch }}
    environment:
      name: wallet
      url: ${{ vars.WEBSITE }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          check-latest: true
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run deploy
      - name: Get clean branch name
        id: clean_branch
        env:
          RM_FEAT: "feat/"
        run: |
          export BRANCH=${GITHUB_REF_NAME//$RM_FEAT/}
          echo "$BRANCH"
          echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"
      - name: Deploy via rsync
        uses: bnnanet/github-actions-rsync@master
        with:
          RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*'
          RSYNC_SOURCE: ./dist/
          RSYNC_TARGET: ~/branch/${{ steps.clean_branch.outputs.branch }}
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_USERNAME: ${{secrets.SSH_USERNAME}}
          SSH_HOSTNAME: ${{secrets.SSH_HOSTNAME}}
          SSH_CONFIG: ${{secrets.SSH_CONFIG}}
